<?php

namespace App\Services\Agents\Handlers;

use App\Models\DataSource;
use App\Models\Summary;
use App\Schemas\MeetingSchema;
use App\Services\Agents\BaseAgent;
use Illuminate\Support\Facades\Log;

class MeetingHandler
{
    public function __construct(private string $orgId, private string $pulseId)
    {
    }

    public function getMeetingSummary(
        BaseAgent $agent,
        array $arguments,
    ): ?string {
        try {
            if (! isset($arguments['meeting_data_source_id'])) {
                return 'Valid meeting_data_source_id is required to use this tool, find the correct data source first.';
            }

            $dataSource = DataSource::find(
                $arguments['meeting_data_source_id'],
            );
            if (! $dataSource) {
                return 'No data source with this id ' .
                    $arguments['meeting_data_source_id'] .
                    '. Find the correct data source first.';
            }

            if (
                is_null($dataSource->origin) || $dataSource->origin->value !== 'meeting'
            ) {
                return 'This tool can only generate meeting data sources, hand over the task to other tools. If none generate yourself';
            }

            $summary = Summary::where(
                'data_source_id',
                $arguments['meeting_data_source_id'],
            )->first();
            if (! $summary) {
                return "This meeting do not have meeting yet.\n 
                Respond to user in this manner\n
                'Hi {name}, Looks like the summary for this meeting is not yet generated by manager. Ask the pulse manager to generate summary first.'\n
                You can also add 1 sentence overview about the meeting in your response";
            }

            $summaryJson = $summary->toJson();

            $response = <<<EOD
Here's the summary:
$summaryJson

However, return just this json format to the user.
```json
{
    "summary": "Short headline with short description for summary. strictly maintain this structure at all times "The [title of meeting] Summary is now available! Highlight key: [key high light of the meeting]",
    "content": [
        {
            "summary_id": "The id (uuid format) of the meeting summary",
            "text": "The title of the summary"
        }
    ]   
}
```

Make sure do not alter the formatting and values.
EOD;

            $agent->setCurrentToolResponseFormat(
                'retrievedMeetingSummary',
                MeetingSchema::GENERATED_SUMMARY,
            );
            return $response;
        } catch (\Exception $e) {
            Log::error('Failed to retrieve Summary: ' . $e->getMessage());

            return 'Cannot retrieve summary at the moment';
        }
    }
}
