import {
  Task,
  TaskPriority,
  TaskStatus,
  TaskType,
} from '@zunou-graphql/core/graphql'

/**
 * Generates dummy task data for demonstration across all views
 */
export const generateDummyTasks = (
  organizationId: string,
  entityId: string,
): Task[] => {
  const now = new Date()
  const baseDate = new Date(now.getFullYear(), now.getMonth(), now.getDate())

  // Helper to create dates
  const addDays = (days: number) => {
    const date = new Date(baseDate)
    date.setDate(date.getDate() + days)
    return date.toISOString().split('T')[0]
  }

  const dummyTasks: Task[] = [
    // Milestone (List)
    {
      __typename: 'Task',
      assignees: [],
      category: null,
      children: [],
      completed_children_count: 0,
      createdAt: addDays(-30) + 'T00:00:00Z',
      createdBy: null,
      description: 'Initial project kickoff meeting and planning',
      due_date: addDays(0),
      entity: null,
      entity_id: entityId,
      entity_type: 'PULSE',
      id: 'dummy-milestone-1',
      order: '0',
      organization: {
        __typename: 'Organization',
        id: organizationId,
      } as unknown as Task['organization'],
      parent: null,
      priority: TaskPriority.High,
      status: TaskStatus.Completed,
      title: 'Project Kickoff',
      type: TaskType.List,
      updatedAt: addDays(0) + 'T00:00:00Z',
      updatedBy: null,
    },
    // Task items under milestone
    {
      __typename: 'Task',
      assignees: [],
      category: null,
      children: [],
      completed_children_count: 0,
      createdAt: addDays(-25) + 'T00:00:00Z',
      createdBy: null,
      description: 'Gather and document all requirements from stakeholders',
      due_date: addDays(7),
      entity: null,
      entity_id: entityId,
      entity_type: 'PULSE',
      id: 'dummy-task-1',
      order: '1',
      organization: {
        __typename: 'Organization',
        id: organizationId,
      } as unknown as Task['organization'],
      parent: {
        __typename: 'Task',
        id: 'dummy-milestone-1',
        title: 'Project Kickoff',
      } as unknown as Task['parent'],
      priority: TaskPriority.High,
      status: TaskStatus.Inprogress,
      title: 'Requirements Gathering',
      type: TaskType.Task,
      updatedAt: addDays(-20) + 'T00:00:00Z',
      updatedBy: null,
    },
    {
      __typename: 'Task',
      assignees: [],
      category: null,
      children: [],
      completed_children_count: 0,
      createdAt: addDays(-20) + 'T00:00:00Z',
      createdBy: null,
      description: 'Create wireframes and mockups for the application',
      due_date: addDays(14),
      entity: null,
      entity_id: entityId,
      entity_type: 'PULSE',
      id: 'dummy-task-2',
      order: '2',
      organization: {
        __typename: 'Organization',
        id: organizationId,
      } as unknown as Task['organization'],
      parent: {
        __typename: 'Task',
        id: 'dummy-milestone-1',
        title: 'Project Kickoff',
      } as unknown as Task['parent'],
      priority: TaskPriority.Medium,
      status: TaskStatus.Todo,
      title: 'Design Phase',
      type: TaskType.Task,
      updatedAt: addDays(-20) + 'T00:00:00Z',
      updatedBy: null,
    },
    // Another milestone
    {
      __typename: 'Task',
      assignees: [],
      category: null,
      children: [],
      completed_children_count: 0,
      createdAt: addDays(-15) + 'T00:00:00Z',
      createdBy: null,
      description: 'Release beta version for testing',
      due_date: addDays(30),
      entity: null,
      entity_id: entityId,
      entity_type: 'PULSE',
      id: 'dummy-milestone-2',
      order: '3',
      organization: {
        __typename: 'Organization',
        id: organizationId,
      } as unknown as Task['organization'],
      parent: null,
      priority: TaskPriority.Urgent,
      status: TaskStatus.Todo,
      title: 'Beta Release',
      type: TaskType.List,
      updatedAt: addDays(-15) + 'T00:00:00Z',
      updatedBy: null,
    },
    // Standalone tasks
    {
      __typename: 'Task',
      assignees: [],
      category: null,
      children: [],
      completed_children_count: 0,
      createdAt: addDays(-10) + 'T00:00:00Z',
      createdBy: null,
      description: 'Core feature development and implementation',
      due_date: addDays(21),
      entity: null,
      entity_id: entityId,
      entity_type: 'PULSE',
      id: 'dummy-task-3',
      order: '4',
      organization: {
        __typename: 'Organization',
        id: organizationId,
      } as unknown as Task['organization'],
      parent: null,
      priority: TaskPriority.High,
      status: TaskStatus.Inprogress,
      title: 'Development Sprint 1',
      type: TaskType.Task,
      updatedAt: addDays(-5) + 'T00:00:00Z',
      updatedBy: null,
    },
    {
      __typename: 'Task',
      assignees: [],
      category: null,
      children: [],
      completed_children_count: 0,
      createdAt: addDays(-5) + 'T00:00:00Z',
      createdBy: null,
      description: 'Quality assurance and bug fixes',
      due_date: addDays(35),
      entity: null,
      entity_id: entityId,
      entity_type: 'PULSE',
      id: 'dummy-task-4',
      order: '5',
      organization: {
        __typename: 'Organization',
        id: organizationId,
      } as unknown as Task['organization'],
      parent: null,
      priority: TaskPriority.Medium,
      status: TaskStatus.Todo,
      title: 'QA Testing',
      type: TaskType.Task,
      updatedAt: addDays(-5) + 'T00:00:00Z',
      updatedBy: null,
    },
    {
      __typename: 'Task',
      assignees: [],
      category: null,
      children: [],
      completed_children_count: 0,
      createdAt: addDays(-2) + 'T00:00:00Z',
      createdBy: null,
      description: 'Deploy to production environment',
      due_date: addDays(45),
      entity: null,
      entity_id: entityId,
      entity_type: 'PULSE',
      id: 'dummy-task-5',
      order: '6',
      organization: {
        __typename: 'Organization',
        id: organizationId,
      } as unknown as Task['organization'],
      parent: null,
      priority: TaskPriority.Urgent,
      status: TaskStatus.Todo,
      title: 'Production Deployment',
      type: TaskType.Task,
      updatedAt: addDays(-2) + 'T00:00:00Z',
      updatedBy: null,
    },
  ]

  return dummyTasks
}
