# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Install system dependencies
RUN apt-get update && \
apt-get install -y \
curl

# prevent from reinstalling everytime
COPY requirements-dev.txt /app/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements-dev.txt
  
# Copy the current directory contents into the container at /app
COPY . /app

# Expose port 8080
EXPOSE 8080

# Run the application
CMD ["gunicorn", "-w 4", "-b 0.0.0.0:8080", "--timeout", "300", "--reload", "flask_processor:app"]